name: Windows Build Electron

on:
  workflow_call:
    inputs:
      uploadArtifacts:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Electron
    runs-on: windows-2022
    # Set some sort of timeout in the event of run-away builds.  We are limited on concurrent jobs so, get rid of them.
    timeout-minutes: 30

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Add Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd .\app\
          npm install

      - name: Install Frontend Dependencies
        run: |
          npm install

      - name: Create environment file
        run: echo "${{ secrets.ENV_CONFIG_FILE }}" > src/environments/environment.ts

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        run: npm run deploy

      - name: Set Tag
        run: echo ("VERSION_VAL=" + $env:GITHUB_REF.replace('refs/tags/v', '')) >> $env:GITHUB_ENV

      - name: Upload Release Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        run: gh release upload $env:GITHUB_REF_NAME dist/teamruns-client-${{env.VERSION_VAL}}-installer.exe dist/teamruns-client-${{env.VERSION_VAL}}-portable.exe --repo JoKronk/release-test-client --clobber

